/** Major US cities for searchable dropdowns. { value: city name, label: "City, ST" } */
export const US_CITIES = [
    { value: 'New York', label: 'New York, NY' },
    { value: 'Los Angeles', label: 'Los Angeles, CA' },
    { value: 'Chicago', label: 'Chicago, IL' },
    { value: 'Houston', label: 'Houston, TX' },
    { value: 'Phoenix', label: 'Phoenix, AZ' },
    { value: 'Philadelphia', label: 'Philadelphia, PA' },
    { value: 'San Antonio', label: 'San Antonio, TX' },
    { value: 'San Diego', label: 'San Diego, CA' },
    { value: 'Dallas', label: 'Dallas, TX' },
    { value: 'San Jose', label: 'San Jose, CA' },
    { value: 'Austin', label: 'Austin, TX' },
    { value: 'Jacksonville', label: 'Jacksonville, FL' },
    { value: 'Fort Worth', label: 'Fort Worth, TX' },
    { value: 'Columbus', label: 'Columbus, OH' },
    { value: 'Charlotte', label: 'Charlotte, NC' },
    { value: 'San Francisco', label: 'San Francisco, CA' },
    { value: 'Indianapolis', label: 'Indianapolis, IN' },
    { value: 'Seattle', label: 'Seattle, WA' },
    { value: 'Denver', label: 'Denver, CO' },
    { value: 'Washington', label: 'Washington, DC' },
    { value: 'Boston', label: 'Boston, MA' },
    { value: 'El Paso', label: 'El Paso, TX' },
    { value: 'Nashville', label: 'Nashville, TN' },
    { value: 'Detroit', label: 'Detroit, MI' },
    { value: 'Oklahoma City', label: 'Oklahoma City, OK' },
    { value: 'Portland', label: 'Portland, OR' },
    { value: 'Las Vegas', label: 'Las Vegas, NV' },
    { value: 'Memphis', label: 'Memphis, TN' },
    { value: 'Louisville', label: 'Louisville, KY' },
    { value: 'Baltimore', label: 'Baltimore, MD' },
    { value: 'Milwaukee', label: 'Milwaukee, WI' },
    { value: 'Albuquerque', label: 'Albuquerque, NM' },
    { value: 'Tucson', label: 'Tucson, AZ' },
    { value: 'Fresno', label: 'Fresno, CA' },
    { value: 'Mesa', label: 'Mesa, AZ' },
    { value: 'Sacramento', label: 'Sacramento, CA' },
    { value: 'Atlanta', label: 'Atlanta, GA' },
    { value: 'Kansas City', label: 'Kansas City, MO' },
    { value: 'Colorado Springs', label: 'Colorado Springs, CO' },
    { value: 'Raleigh', label: 'Raleigh, NC' },
    { value: 'Miami', label: 'Miami, FL' },
    { value: 'Long Beach', label: 'Long Beach, CA' },
    { value: 'Virginia Beach', label: 'Virginia Beach, VA' },
    { value: 'Omaha', label: 'Omaha, NE' },
    { value: 'Oakland', label: 'Oakland, CA' },
    { value: 'Minneapolis', label: 'Minneapolis, MN' },
    { value: 'Tulsa', label: 'Tulsa, OK' },
    { value: 'Tampa', label: 'Tampa, FL' },
    { value: 'Arlington', label: 'Arlington, TX' },
    { value: 'New Orleans', label: 'New Orleans, LA' },
    { value: 'Wichita', label: 'Wichita, KS' },
    { value: 'Cleveland', label: 'Cleveland, OH' },
    { value: 'Bakersfield', label: 'Bakersfield, CA' },
    { value: 'Aurora', label: 'Aurora, CO' },
    { value: 'Honolulu', label: 'Honolulu, HI' },
    { value: 'Anaheim', label: 'Anaheim, CA' },
    { value: 'Santa Ana', label: 'Santa Ana, CA' },
    { value: 'St. Louis', label: 'St. Louis, MO' },
    { value: 'Riverside', label: 'Riverside, CA' },
    { value: 'Corpus Christi', label: 'Corpus Christi, TX' },
    { value: 'Lexington', label: 'Lexington, KY' },
    { value: 'Pittsburgh', label: 'Pittsburgh, PA' },
    { value: 'Anchorage', label: 'Anchorage, AK' },
    { value: 'Stockton', label: 'Stockton, CA' },
    { value: 'Cincinnati', label: 'Cincinnati, OH' },
    { value: 'St. Paul', label: 'St. Paul, MN' },
    { value: 'Toledo', label: 'Toledo, OH' },
    { value: 'Newark', label: 'Newark, NJ' },
    { value: 'Greensboro', label: 'Greensboro, NC' },
    { value: 'Plano', label: 'Plano, TX' },
    { value: 'Henderson', label: 'Henderson, NV' },
    { value: 'Lincoln', label: 'Lincoln, NE' },
    { value: 'Buffalo', label: 'Buffalo, NY' },
    { value: 'Fort Wayne', label: 'Fort Wayne, IN' },
    { value: 'Jersey City', label: 'Jersey City, NJ' },
    { value: 'St. Petersburg', label: 'St. Petersburg, FL' },
    { value: 'Chula Vista', label: 'Chula Vista, CA' },
    { value: 'Orlando', label: 'Orlando, FL' },
    { value: 'Norfolk', label: 'Norfolk, VA' },
    { value: 'Chandler', label: 'Chandler, AZ' },
    { value: 'Laredo', label: 'Laredo, TX' },
    { value: 'Madison', label: 'Madison, WI' },
    { value: 'Winston-Salem', label: 'Winston-Salem, NC' },
    { value: 'Lubbock', label: 'Lubbock, TX' },
    { value: 'Baton Rouge', label: 'Baton Rouge, LA' },
    { value: 'Durham', label: 'Durham, NC' },
    { value: 'Garland', label: 'Garland, TX' },
    { value: 'Glendale', label: 'Glendale, AZ' },
    { value: 'Reno', label: 'Reno, NV' },
    { value: 'Hialeah', label: 'Hialeah, FL' },
    { value: 'Birmingham', label: 'Birmingham, AL' },
    { value: 'Richmond', label: 'Richmond, VA' },
    { value: 'San Bernardino', label: 'San Bernardino, CA' },
    { value: 'Spokane', label: 'Spokane, WA' },
    { value: 'Rochester', label: 'Rochester, NY' },
    { value: 'Des Moines', label: 'Des Moines, IA' },
    { value: 'Modesto', label: 'Modesto, CA' },
    { value: 'Fremont', label: 'Fremont, CA' },
    { value: 'Boise', label: 'Boise, ID' },
    { value: 'Salt Lake City', label: 'Salt Lake City, UT' },
    { value: 'Grand Rapids', label: 'Grand Rapids, MI' },
    { value: 'Huntsville', label: 'Huntsville, AL' },
    { value: 'Grand Prairie', label: 'Grand Prairie, TX' },
    { value: 'Yonkers', label: 'Yonkers, NY' },
    { value: 'Aurora', label: 'Aurora, IL' },
    { value: 'Montgomery', label: 'Montgomery, AL' },
    { value: 'Amarillo', label: 'Amarillo, TX' },
    { value: 'Akron', label: 'Akron, OH' },
    { value: 'Little Rock', label: 'Little Rock, AR' },
    { value: 'Columbus', label: 'Columbus, GA' },
    { value: 'Augusta', label: 'Augusta, GA' },
    { value: 'Tallahassee', label: 'Tallahassee, FL' },
    { value: 'Overland Park', label: 'Overland Park, KS' },
    { value: 'Tempe', label: 'Tempe, AZ' },
    { value: 'McKinney', label: 'McKinney, TX' },
    { value: 'Mobile', label: 'Mobile, AL' },
    { value: 'Cape Coral', label: 'Cape Coral, FL' },
    { value: 'Shreveport', label: 'Shreveport, LA' },
    { value: 'Frisco', label: 'Frisco, TX' },
    { value: 'Knoxville', label: 'Knoxville, TN' },
    { value: 'Worcester', label: 'Worcester, MA' },
    { value: 'Newport News', label: 'Newport News, VA' },
    { value: 'Brownsville', label: 'Brownsville, TX' },
    { value: 'Santa Clarita', label: 'Santa Clarita, CA' },
    { value: 'Providence', label: 'Providence, RI' },
    { value: 'Vancouver', label: 'Vancouver, WA' },
    { value: 'Ontario', label: 'Ontario, CA' },
    { value: 'Garden Grove', label: 'Garden Grove, CA' },
    { value: 'Chattanooga', label: 'Chattanooga, TN' },
    { value: 'Oceanside', label: 'Oceanside, CA' },
    { value: 'Fort Lauderdale', label: 'Fort Lauderdale, FL' },
    { value: 'Rancho Cucamonga', label: 'Rancho Cucamonga, CA' },
    { value: 'Santa Rosa', label: 'Santa Rosa, CA' },
    { value: 'Port St. Lucie', label: 'Port St. Lucie, FL' },
    { value: 'Temecula', label: 'Temecula, CA' },
    { value: 'Springfield', label: 'Springfield, MO' },
    { value: 'Cary', label: 'Cary, NC' },
    { value: 'Rockford', label: 'Rockford, IL' },
    { value: 'Pembroke Pines', label: 'Pembroke Pines, FL' },
    { value: 'Salinas', label: 'Salinas, CA' },
    { value: 'Pomona', label: 'Pomona, CA' },
    { value: 'Pasadena', label: 'Pasadena, TX' },
    { value: 'Kansas City', label: 'Kansas City, KS' },
    { value: 'Torrance', label: 'Torrance, CA' },
    { value: 'Syracuse', label: 'Syracuse, NY' },
    { value: 'Bridgeport', label: 'Bridgeport, CT' },
    { value: 'Hayward', label: 'Hayward, CA' },
    { value: 'Fort Collins', label: 'Fort Collins, CO' },
    { value: 'Corona', label: 'Corona, CA' },
    { value: 'Savannah', label: 'Savannah, GA' },
    { value: 'Mesquite', label: 'Mesquite, TX' },
    { value: 'Sunnyvale', label: 'Sunnyvale, CA' },
    { value: 'Hollywood', label: 'Hollywood, FL' },
    { value: 'Orange', label: 'Orange, CA' },
    { value: 'Naperville', label: 'Naperville, IL' },
    { value: 'Alexandria', label: 'Alexandria, VA' },
    { value: 'Palm Bay', label: 'Palm Bay, FL' },
    { value: 'Pomona', label: 'Pomona, CA' },
    { value: 'Lake Forest', label: 'Lake Forest, CA' },
    { value: 'Springfield', label: 'Springfield, MA' },
    { value: 'Salem', label: 'Salem, OR' },
    { value: 'Paterson', label: 'Paterson, NJ' },
    { value: 'Hampton', label: 'Hampton, VA' },
    { value: 'Santa Clara', label: 'Santa Clara, CA' },
    { value: 'Eugene', label: 'Eugene, OR' },
    { value: 'Vallejo', label: 'Vallejo, CA' },
    { value: 'Dayton', label: 'Dayton, OH' },
    { value: 'Elk Grove', label: 'Elk Grove, CA' },
    { value: 'Springfield', label: 'Springfield, IL' },
    { value: 'New Haven', label: 'New Haven, CT' },
    { value: 'Miami Beach', label: 'Miami Beach, FL' },
    { value: 'Concord', label: 'Concord, CA' },
    { value: 'Coral Springs', label: 'Coral Springs, FL' },
    { value: 'Roseville', label: 'Roseville, CA' },
    { value: 'Thornton', label: 'Thornton, CO' },
    { value: 'Sioux Falls', label: 'Sioux Falls, SD' },
    { value: 'Elizabeth', label: 'Elizabeth, NJ' },
    { value: 'Kent', label: 'Kent, WA' },
    { value: 'Lancaster', label: 'Lancaster, CA' },
    { value: 'Sterling Heights', label: 'Sterling Heights, MI' },
    { value: 'Warren', label: 'Warren, MI' },
    { value: 'Bellevue', label: 'Bellevue, WA' },
    { value: 'West Valley City', label: 'West Valley City, UT' },
    { value: 'Columbia', label: 'Columbia, SC' },
    { value: 'Denton', label: 'Denton, TX' },
    { value: 'Midland', label: 'Midland, TX' },
    { value: 'Norman', label: 'Norman, OK' },
    { value: 'Athens', label: 'Athens, GA' },
    { value: 'Columbia', label: 'Columbia, MO' },
    { value: 'Abilene', label: 'Abilene, TX' },
    { value: 'Berkeley', label: 'Berkeley, CA' },
    { value: 'Richardson', label: 'Richardson, TX' },
    { value: 'Redding', label: 'Redding, CA' },
    { value: 'Arvada', label: 'Arvada, CO' },
    { value: 'East Los Angeles', label: 'East Los Angeles, CA' },
    { value: 'St. George', label: 'St. George, UT' },
    { value: 'Billings', label: 'Billings, MT' },
    { value: 'Yuba City', label: 'Yuba City, CA' },
    { value: 'Rochester', label: 'Rochester, MN' },
    { value: 'Lehigh Acres', label: 'Lehigh Acres, FL' },
    { value: 'Fayetteville', label: 'Fayetteville, NC' },
    { value: 'Buckeye', label: 'Buckeye, AZ' },
    { value: 'Apex', label: 'Apex, NC' },
    { value: 'Wilmington', label: 'Wilmington, NC' },
    { value: 'Arlington', label: 'Arlington, VA' },
    { value: 'Sarasota', label: 'Sarasota, FL' },
    { value: 'Ann Arbor', label: 'Ann Arbor, MI' },
    { value: 'Green Bay', label: 'Green Bay, WI' },
    { value: 'Boulder', label: 'Boulder, CO' },
    { value: 'Edison', label: 'Edison, NJ' },
    { value: 'Davenport', label: 'Davenport, IA' },
    { value: 'Woodbridge', label: 'Woodbridge, NJ' },
    { value: 'Rialto', label: 'Rialto, CA' },
    { value: 'Las Cruces', label: 'Las Cruces, NM' },
    { value: 'San Mateo', label: 'San Mateo, CA' },
    { value: 'Lewisville', label: 'Lewisville, TX' },
    { value: 'Lakeland', label: 'Lakeland, FL' },
    { value: 'Erie', label: 'Erie, PA' },
    { value: 'Tyler', label: 'Tyler, TX' },
    { value: 'Pearland', label: 'Pearland, TX' },
    { value: 'College Station', label: 'College Station, TX' },
    { value: 'Kenosha', label: 'Kenosha, WI' },
    { value: 'Sandy Springs', label: 'Sandy Springs, GA' },
    { value: 'Clovis', label: 'Clovis, CA' },
    { value: 'Watsonville', label: 'Watsonville, CA' }
]
